### PR TITLE
Fix null data on breadcrumb.

### PR DESCRIPTION
**Pull request by lucas-zimerman**
Solves #88.

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]

**Comment by thiagoloureiro** [comment]
guys, this is included on 1.3.1 or there are any prevision to release?

**Comment by lucas-zimerman** [comment]
> guys, this is included on 1.3.1 or there are any prevision to release? (Edit) I see 1.3.1 is from november, and this was pushed in December, @bruno-garcia any plans to release 1.3.2? :) obrigado ;)

We'll update the PR https://github.com/getsentry/sentry-xamarin/pull/93 to point to the latest version of Sentry and include this merge soon.

**Comment by bruno-garcia** [comment]
> guys, this is included on 1.3.1 or there are any prevision to release? (Edit) I see 1.3.1 is from november, and this was pushed in December, @bruno-garcia any plans to release 1.3.2? :) obrigado ;)

Shipped: https://github.com/getsentry/sentry-xamarin/releases

**Comment by thiagoloureiro** [comment]
Cheers Bruno!

**Pull request merged**
